import type { FormattedAnalysis } from './formatter';

/**
 * Generate JSON export of the analysis
 */
export function generateExportJSON(analysis: FormattedAnalysis): string {
  const exportData = {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    analysis: {
      ...analysis,
      _disclaimer: 'Analysis generated by NicheHunter AI Glass Engine™',
    },
  };

  return JSON.stringify(exportData, null, 2);
}

/**
 * Generate Markdown report of the analysis
 */
export function generateExportMarkdown(analysis: FormattedAnalysis): string {
  const lines: string[] = [];

  // Header
  lines.push(`# NicheHunter AI Analysis Report`);
  lines.push('');
  lines.push(`## ${analysis.meta.videoTitle}`);
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Duration | ${analysis.meta.duration} |`);
  lines.push(`| Overall Grade | ${analysis.meta.grade} (${analysis.meta.gradeLabel}) |`);
  lines.push(`| Overall Score | ${analysis.meta.overallScore}% |`);
  lines.push(`| Analyzed | ${new Date(analysis.meta.analyzedAt).toLocaleString()} |`);
  lines.push('');

  // Executive Summary
  lines.push(`## Executive Summary`);
  lines.push('');
  lines.push(`> ${analysis.executive.verdict}`);
  lines.push('');
  lines.push(analysis.executive.summary);
  lines.push('');

  // Key Insights
  lines.push(`### Key Strengths`);
  analysis.executive.keyStrengths.forEach((s) => lines.push(`- ✅ ${s}`));
  lines.push('');

  lines.push(`### Areas for Improvement`);
  analysis.executive.keyImprovements.forEach((i) => lines.push(`- ⚠️ ${i}`));
  lines.push('');

  lines.push(`### Action Items`);
  analysis.executive.actionItems.forEach((a, idx) => lines.push(`${idx + 1}. ${a}`));
  lines.push('');

  // Hook Analysis
  lines.push(`## Hook Analysis`);
  lines.push('');
  lines.push(`**Type:** ${analysis.sections.hook.type}`);
  lines.push(`**Score:** ${analysis.sections.hook.score}% (${analysis.sections.hook.scoreLabel})`);
  lines.push('');
  lines.push(`**Opening:**`);
  lines.push(`> "${analysis.sections.hook.opening}"`);
  lines.push('');
  lines.push(`**Analysis:** ${analysis.sections.hook.analysis}`);
  lines.push('');
  if (analysis.sections.hook.strengths.length > 0) {
    lines.push(`**Strengths:**`);
    analysis.sections.hook.strengths.forEach((s) => lines.push(`- ${s}`));
    lines.push('');
  }
  if (analysis.sections.hook.weaknesses.length > 0) {
    lines.push(`**Weaknesses:**`);
    analysis.sections.hook.weaknesses.forEach((w) => lines.push(`- ${w}`));
    lines.push('');
  }
  lines.push(`**Recommendation:** ${analysis.sections.hook.recommendation}`);
  lines.push('');

  // Retention Analysis
  lines.push(`## Retention Analysis`);
  lines.push('');
  lines.push(`**Overall Score:** ${analysis.sections.retention.score}% (${analysis.sections.retention.scoreLabel})`);
  lines.push('');

  if (analysis.sections.retention.timeline.length > 0) {
    lines.push(`### Timeline`);
    lines.push('');
    lines.push(`| Time | Segment | Score | Insight |`);
    lines.push(`|------|---------|-------|---------|`);
    analysis.sections.retention.timeline.forEach((t) => {
      lines.push(`| ${t.time} | ${t.label} | ${t.score}% | ${t.insight} |`);
    });
    lines.push('');
  }

  if (analysis.sections.retention.patternInterrupts.length > 0) {
    lines.push(`### Pattern Interrupts`);
    analysis.sections.retention.patternInterrupts.forEach((p) => {
      lines.push(`- **${p.time}** - ${p.type}`);
    });
    lines.push('');
  }

  if (analysis.sections.retention.weakSpots.length > 0) {
    lines.push(`### Weak Spots`);
    analysis.sections.retention.weakSpots.forEach((w) => {
      lines.push(`- **${w.time}** - ${w.issue}`);
    });
    lines.push('');
  }

  lines.push(`**Recommendation:** ${analysis.sections.retention.recommendation}`);
  lines.push('');

  // Structure Analysis
  lines.push(`## Structure Analysis`);
  lines.push('');
  lines.push(`**Framework:** ${analysis.sections.structure.framework}`);
  lines.push(`**Score:** ${analysis.sections.structure.score}% (${analysis.sections.structure.scoreLabel})`);
  lines.push(`**Flow:** ${analysis.sections.structure.flow}`);
  lines.push('');

  if (analysis.sections.structure.sections.length > 0) {
    lines.push(`### Sections`);
    lines.push('');
    lines.push(`| Section | Time | Effectiveness |`);
    lines.push(`|---------|------|---------------|`);
    analysis.sections.structure.sections.forEach((s) => {
      lines.push(`| ${s.type} | ${s.timeRange} | ${s.effectiveness} |`);
    });
    lines.push('');
  }

  if (analysis.sections.structure.recommendations.length > 0) {
    lines.push(`### Recommendations`);
    analysis.sections.structure.recommendations.forEach((r) => lines.push(`- ${r}`));
    lines.push('');
  }

  // Visual Analysis
  lines.push(`## Visual Analysis`);
  lines.push('');
  lines.push(`**Style:** ${analysis.sections.visual.style}`);
  lines.push(`**Editing:** ${analysis.sections.visual.editingStyle}`);
  lines.push('');
  lines.push(`### Metrics`);
  lines.push(`| Metric | Value | Assessment |`);
  lines.push(`|--------|-------|------------|`);
  lines.push(
    `| Face Presence | ${analysis.sections.visual.metrics.facePresence.value}% | ${analysis.sections.visual.metrics.facePresence.label} |`
  );
  lines.push(
    `| Text Overlays | ${analysis.sections.visual.metrics.textOverlays.value}% | ${analysis.sections.visual.metrics.textOverlays.label} |`
  );
  lines.push(
    `| Scene Changes | ${analysis.sections.visual.metrics.sceneChanges.value}% | ${analysis.sections.visual.metrics.sceneChanges.label} |`
  );
  lines.push(
    `| B-Roll Usage | ${analysis.sections.visual.metrics.brollUsage.value}% | ${analysis.sections.visual.metrics.brollUsage.label} |`
  );
  lines.push('');

  if (analysis.sections.visual.dominantColors.length > 0) {
    lines.push(`**Dominant Colors:** ${analysis.sections.visual.dominantColors.join(', ')}`);
    lines.push('');
  }

  // Persona Analysis
  lines.push(`## Persona Analysis`);
  lines.push('');
  lines.push(`**Archetype:** ${analysis.sections.persona.archetype}`);
  lines.push(`**Score:** ${analysis.sections.persona.score}% (${analysis.sections.persona.scoreLabel})`);
  lines.push('');
  lines.push(`**Voice:** ${analysis.sections.persona.voiceDescription}`);
  lines.push('');
  lines.push(`### Traits`);
  lines.push(`| Trait | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| Speaking Pace | ${analysis.sections.persona.traits.speakingPace} |`);
  lines.push(`| Words Per Minute | ${analysis.sections.persona.traits.wordsPerMinute} |`);
  lines.push(
    `| Authority | ${analysis.sections.persona.traits.authority.score}% (${analysis.sections.persona.traits.authority.label}) |`
  );
  lines.push(
    `| Relatability | ${analysis.sections.persona.traits.relatability.score}% (${analysis.sections.persona.traits.relatability.label}) |`
  );
  lines.push(`| Energy Level | ${analysis.sections.persona.traits.energy} |`);
  lines.push(`| Persuasion Style | ${analysis.sections.persona.traits.persuasionStyle} |`);
  lines.push('');

  // Platform Recommendations
  lines.push(`## Platform Recommendations`);
  lines.push('');

  analysis.platforms.forEach((platform) => {
    lines.push(`### ${platform.name}`);
    lines.push(`**Compatibility:** ${platform.compatibility}% (${platform.compatibilityLabel})`);
    lines.push('');

    if (platform.tips.length > 0) {
      lines.push(`**Tips:**`);
      platform.tips.forEach((t) => lines.push(`- ${t}`));
      lines.push('');
    }

    if (platform.warnings.length > 0) {
      lines.push(`**Warnings:**`);
      platform.warnings.forEach((w) => lines.push(`- ⚠️ ${w}`));
      lines.push('');
    }

    if (platform.optimizations.length > 0) {
      lines.push(`**Optimizations:**`);
      platform.optimizations.forEach((o) => lines.push(`- ${o}`));
      lines.push('');
    }
  });

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Analysis powered by Glass Engine™ • NicheHunter AI*`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate a shareable link-friendly summary
 */
export function generateShareableLink(analysis: FormattedAnalysis): ShareableData {
  return {
    v: 1, // version
    i: analysis.meta.id,
    t: analysis.meta.videoTitle.slice(0, 50),
    g: analysis.meta.grade,
    s: analysis.meta.overallScore,
    h: {
      t: analysis.sections.hook.type.slice(0, 20),
      s: analysis.sections.hook.score,
    },
    r: analysis.sections.retention.score,
    f: analysis.sections.structure.framework.slice(0, 10),
    p: analysis.sections.persona.archetype.slice(0, 15),
    pl: analysis.platforms.slice(0, 2).map((p) => ({
      n: p.name.slice(0, 10),
      c: p.compatibility,
    })),
  };
}

export interface ShareableData {
  v: number;
  i: string;
  t: string;
  g: string;
  s: number;
  h: { t: string; s: number };
  r: number;
  f: string;
  p: string;
  pl: Array<{ n: string; c: number }>;
}

/**
 * Encode shareable data to URL-safe string (browser-compatible)
 */
export function encodeShareableData(data: ShareableData): string {
  const json = JSON.stringify(data);
  // Base64 encode and make URL-safe (using btoa for browser compatibility)
  const base64 = typeof window !== 'undefined'
    ? btoa(unescape(encodeURIComponent(json)))
    : Buffer.from(json).toString('base64');
  return base64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
}

/**
 * Decode shareable data from URL-safe string (browser-compatible)
 */
export function decodeShareableData(encoded: string): ShareableData | null {
  try {
    // Restore Base64 format
    let base64 = encoded.replace(/-/g, '+').replace(/_/g, '/');
    // Add padding if needed
    while (base64.length % 4) {
      base64 += '=';
    }
    // Use atob for browser compatibility
    const json = typeof window !== 'undefined'
      ? decodeURIComponent(escape(atob(base64)))
      : Buffer.from(base64, 'base64').toString('utf8');
    return JSON.parse(json);
  } catch {
    return null;
  }
}

/**
 * Generate plain text summary for clipboard/social sharing
 */
export function generateTextSummary(analysis: FormattedAnalysis): string {
  const lines: string[] = [];

  lines.push(`📊 NicheHunter AI Analysis`);
  lines.push('');
  lines.push(`🎬 ${analysis.meta.videoTitle}`);
  lines.push(`⏱️ Duration: ${analysis.meta.duration}`);
  lines.push('');
  lines.push(`🏆 Grade: ${analysis.meta.grade} (${analysis.meta.gradeLabel})`);
  lines.push(`📈 Score: ${analysis.meta.overallScore}%`);
  lines.push('');
  lines.push(`🎣 Hook: ${analysis.sections.hook.type} (${analysis.sections.hook.score}%)`);
  lines.push(`📐 Structure: ${analysis.sections.structure.framework}`);
  lines.push(`🎭 Persona: ${analysis.sections.persona.archetype}`);
  lines.push('');

  if (analysis.executive.keyStrengths.length > 0) {
    lines.push(`✅ Top Strength: ${analysis.executive.keyStrengths[0]}`);
  }

  if (analysis.executive.actionItems.length > 0) {
    lines.push(`💡 Quick Win: ${analysis.executive.actionItems[0]}`);
  }

  lines.push('');
  lines.push(`Analyze your content: nichehunter.ai`);

  return lines.join('\n');
}

/**
 * Generate CSV export for data analysis
 */
export function generateExportCSV(analyses: FormattedAnalysis[]): string {
  const headers = [
    'Video Title',
    'Duration',
    'Grade',
    'Overall Score',
    'Hook Type',
    'Hook Score',
    'Retention Score',
    'Framework',
    'Structure Score',
    'Persona',
    'Persona Score',
    'Top Platform',
    'Platform Score',
    'Analyzed At',
  ];

  const rows = analyses.map((a) => [
    `"${a.meta.videoTitle.replace(/"/g, '""')}"`,
    a.meta.duration,
    a.meta.grade,
    a.meta.overallScore,
    a.sections.hook.type,
    a.sections.hook.score,
    a.sections.retention.score,
    a.sections.structure.framework,
    a.sections.structure.score,
    a.sections.persona.archetype,
    a.sections.persona.score,
    a.platforms[0]?.name || 'N/A',
    a.platforms[0]?.compatibility || 0,
    a.meta.analyzedAt,
  ]);

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
}
